package com.tratumtech.edugreat.tool;


import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;

import org.codehaus.jettison.json.JSONException;
import org.codehaus.jettison.json.JSONObject;

/**
 * Student generated by hbm2java
 */
public class Student {

	private int id;
	private Integer PId;
	private String firstName;
	private String lastName;
	private String email;
	private String phone;
	private String passw;
	private String institution;
	private Integer standard;
	private String location;
	private Date dob;

	public Student() {
	}

	public Student(int id, Integer PId, String firstName, String lastName, String email, String phone, String passw,
			String institution, Integer standard, String location, Date dob) {
		this.id = id;
		this.PId = PId;
		this.firstName = firstName;
		this.lastName = lastName;
		this.email = email;
		this.phone = phone;
		this.passw = passw;
		this.institution = institution;
		this.standard = standard;
		this.location = location;
		this.dob = dob;
	}
	
	public Student(JSONObject joStudent){
		try {
				if(joStudent.has("id"))
					this.id = joStudent.getInt("id");
				
				if(joStudent.has("PId"))
					this.PId = joStudent.getInt("PId");
				
				if(joStudent.has("firstName"))
					this.firstName = joStudent.getString("firstName");
				
				if(joStudent.has("lastName"))
					this.lastName = joStudent.getString("lastName");
				
				if(joStudent.has("email"))
					this.email = joStudent.getString("email");
				
				if(joStudent.has("phone"))
					this.phone = joStudent.getString("phone");
				
				if(joStudent.has("passw"))
					this.passw = joStudent.getString("passw");
				
				if(joStudent.has("institution"))
					this.institution = joStudent.getString("institution");
				
				if(joStudent.has("standard"))
					this.standard = joStudent.getInt("standard");
				
				if(joStudent.has("location"))
					this.location = joStudent.getString("location");
				
				if(joStudent.has("dob")) {
					String dateStr = joStudent.getString("dob");
					SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
					try {
						this.dob = sdf.parse(dateStr);
					} catch (ParseException e) {
						// TODO Auto-generated catch block
						e.printStackTrace();
					}
				}
				
			} catch (JSONException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
	}
	
	
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Integer getPId() {
		return this.PId;
	}

	public void setPId(Integer PId) {
		this.PId = PId;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getPassw() {
		return this.passw;
	}

	public void setPassw(String passw) {
		this.passw = passw;
	}

	public String getInstitution() {
		return this.institution;
	}

	public void setInstitution(String institution) {
		this.institution = institution;
	}

	public Integer getStandard() {
		return this.standard;
	}

	public void setStandard(Integer standard) {
		this.standard = standard;
	}

	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	public Date getDob() {
		return this.dob;
	}

	public void setDob(Date dob) {
		this.dob = dob;
	}

}
